=== RuMoHoR/bg-chess/BGChess.dtd
<!ENTITY nbsp "&#160;">

<!ELEMENT BGChess ( BGChessCategory+ )>

<!ELEMENT BGChessCategory ( BGChessCategoryName, BGChessCategoryBlock )>
<!ATTLIST BGChessCategory Prefix CDATA #REQUIRED>

<!ELEMENT BGChessCategoryName ( #PCDATA )>

<!ELEMENT BGChessCategoryBlock EMPTY >

=== RuMoHoR/bg-chess/src/BG12Novg/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd" >
<BGChess paginate="yes" >

	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="4" >
		<BGChessCategoryName>Лев</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG12Zhuk/KP70-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess KP="70" paginate="yes">

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BGK12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../BGChess.dtd">
<BGChess>

	<BGChessCategory Prefix="2" >
		<BGChessCategoryName>Атлант</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L4" >
		<BGChessCategoryName>Лев-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P4" >
		<BGChessCategoryName>Лев-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="7" >
		<BGChessCategoryName>Сфинкс</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="9" >
		<BGChessCategoryName>Химера</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG13Tver/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess paginate="yes">

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L4" >
		<BGChessCategoryName>Лев-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P4" >
		<BGChessCategoryName>Лев-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="7" >
		<BGChessCategoryName>Сфинкс</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG12Kir/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd" >
<BGChess paginate="yes" >

	<BGChessCategory Prefix="4" >
		<BGChessCategoryName>Лев</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="7" >
		<BGChessCategoryName>Сфинкс</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BGM12KP200.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "BGChess.dtd">
<BGChess>
	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>
	<BGChessCategory Prefix="L3">
		<BGChessCategoryName>Всадник-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>
	<BGChessCategory Prefix="P7" >
		<BGChessCategoryName>Сфинкс-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>
	<BGChessCategory Prefix="P8">
		<BGChessCategoryName>Грифон-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>
</BGChess>

=== RuMoHoR/bg-chess/src/BG12Zhuk/KP90-unite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess KP="90" paginate="no">

	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG13Msk/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess paginate="yes">

	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="2" >
		<BGChessCategoryName>Атлант</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L6" >
		<BGChessCategoryName>Броневик-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P6" >
		<BGChessCategoryName>Броневик-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L3" >
		<BGChessCategoryName>Всадник-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="M3" >
		<BGChessCategoryName>Всадник-Мидл</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P3" >
		<BGChessCategoryName>Всадник-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L8" >
		<BGChessCategoryName>Грифон-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P8" >
		<BGChessCategoryName>Грифон-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L4" >
		<BGChessCategoryName>Лев-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBreak />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P4" >
		<BGChessCategoryName>Лев-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBreak />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="X4" >
		<BGChessCategoryName>Лев-Экстра</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBreak />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L5" >
		<BGChessCategoryName>Роллер/Химера-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P5" >
		<BGChessCategoryName>Роллер/Химера-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L7" >
		<BGChessCategoryName>Сфинкс-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="M7" >
		<BGChessCategoryName>Сфинкс-Мидл</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P7" >
		<BGChessCategoryName>Сфинкс-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>
