=== RuMoHoR/bg-chess/BGChess.dtd
<!ENTITY nbsp "&#160;">

<!ELEMENT BGChess ( BGChessCategory+ )>

<!ELEMENT BGChessCategory ( BGChessCategoryName, BGChessCategoryBlock )>
<!ATTLIST BGChessCategory Prefix CDATA #REQUIRED>

<!ELEMENT BGChessCategoryName ( #PCDATA )>

<!ELEMENT BGChessCategoryBlock EMPTY >

=== RuMoHoR/bg-chess/src/BG12Ekb/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess paginate="yes">

	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="4" >
		<BGChessCategoryName>Лев</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="7" >
		<BGChessCategoryName>Сфинкс</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG12Spb/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd" >
<BGChess paginate="yes" >

	<BGChessCategory Prefix="L4" >
		<BGChessCategoryName>Лев-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P4" >
		<BGChessCategoryName>Лев-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="_" >
		<BGChessCategoryName>______</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG14Ekb/KPxx-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess paginate="yes">

	<BGChessCategory Prefix="2" >
		<BGChessCategoryName>Атлант</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="4" >
		<BGChessCategoryName>Лев</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="9" >
		<BGChessCategoryName>Лев &amp; Единорог</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="7" >
		<BGChessCategoryName>Сфинкс</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>

=== RuMoHoR/bg-chess/src/BG12Zhuk/KP30-split.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BGChess SYSTEM "../../BGChess.dtd">
<BGChess KP="30" paginate="yes">

	<BGChessCategory Prefix="1" >
		<BGChessCategoryName>Ангел</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="6" >
		<BGChessCategoryName>Броневик</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="3" >
		<BGChessCategoryName>Всадник</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="8" >
		<BGChessCategoryName>Грифон</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="L4" >
		<BGChessCategoryName>Лев-Лайт</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

	<BGChessCategory Prefix="P4" >
		<BGChessCategoryName>Лев-Про</BGChessCategoryName>
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
		<BGChessCategoryBlock />
	</BGChessCategory>

</BGChess>
